"""Generate organization index / catalog page listing all projects."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Dict, List

if TYPE_CHECKING:
    from todocs.core import ProjectProfile


class OrgIndexGenerator:
    """Generate an index.md catalog page for all projects in an organization."""

    def __init__(self, org_name: str = "WronAI", org_url: str = "https://github.com/wronai"):
        self.org_name = org_name
        self.org_url = org_url
        self.generated_at = datetime.now().strftime("%Y-%m-%d")

    def generate(self, profiles: List["ProjectProfile"], output_path: Path) -> None:
        """Generate the index page and write to file."""
        md = self.render(profiles)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(md, encoding="utf-8")

    def render(self, profiles: List["ProjectProfile"]) -> str:
        """Render the full index page as markdown."""
        sections = [
            self._frontmatter(len(profiles)),
            self._header(len(profiles)),
            self._quick_stats(profiles),
            self._category_sections(profiles),
            self._alphabetical_index(profiles),
            self._footer(),
        ]
        return "\n\n".join(s for s in sections if s)

    # ── Section renderers ──────────────────────────────────────────

    def _frontmatter(self, count: int) -> str:
        return "\n".join([
            "---",
            f'title: "{self.org_name} — Project Index"',
            f'slug: "index"',
            f'date: "{self.generated_at}"',
            f'category: "Index"',
            f'project_count: {count}',
            f'generated_by: "todocs"',
            "---",
        ])

    def _header(self, count: int) -> str:
        return "\n".join([
            f"# {self.org_name} — Project Index",
            "",
            f"Catalog of **{count}** projects in the {self.org_name} organization.",
        ])

    def _quick_stats(self, profiles: List["ProjectProfile"]) -> str:
        if not profiles:
            return ""

        total_sloc = sum(p.code_stats.source_lines for p in profiles)
        total_files = sum(p.code_stats.source_files for p in profiles)
        categories = len(set(p.category for p in profiles))
        languages = len(set(p.tech_stack.primary_language for p in profiles))

        return "\n".join([
            "## At a Glance",
            "",
            f"- **{len(profiles)}** projects",
            f"- **{total_sloc:,}** lines of source code",
            f"- **{total_files:,}** source files",
            f"- **{categories}** categories",
            f"- **{languages}** primary languages",
        ])

    def _category_sections(self, profiles: List["ProjectProfile"]) -> str:
        categories: Dict[str, List["ProjectProfile"]] = {}
        for p in profiles:
            categories.setdefault(p.category, []).append(p)

        parts = ["## Projects by Category"]

        for cat, projs in sorted(categories.items()):
            parts.append("")
            parts.append(f"### {cat} ({len(projs)})")
            parts.append("")
            parts.append("| Project | Version | Language | SLOC | Grade |")
            parts.append("|---------|---------|----------|-----:|:-----:|")

            for p in sorted(projs, key=lambda x: x.name):
                ver = p.metadata.version or "—"
                lang = p.tech_stack.primary_language
                sloc = f"{p.code_stats.source_lines:,}"
                grade = p.maturity.grade
                link = f"[{p.name}]({p.name}.md)"
                parts.append(f"| {link} | {ver} | {lang} | {sloc} | {grade} |")

        return "\n".join(parts)

    def _alphabetical_index(self, profiles: List["ProjectProfile"]) -> str:
        lines = ["## Alphabetical Index", ""]
        for p in sorted(profiles, key=lambda x: x.name.lower()):
            desc = p.metadata.description or ""
            if len(desc) > 60:
                desc = desc[:57] + "..."
            entry = f"- **[{p.name}]({p.name}.md)** — {desc}" if desc else f"- **[{p.name}]({p.name}.md)**"
            lines.append(entry)
        return "\n".join(lines)

    def _footer(self) -> str:
        return "\n".join([
            "---",
            "",
            f"*Generated by [todocs](https://github.com/wronai/todocs) on {self.generated_at}.*",
        ])
