"""Generate WordPress-ready project card (single project summary card)."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, List

from .base import BaseGenerator

if TYPE_CHECKING:
    from todocs.core import ProjectProfile


class ProjectCardGenerator(BaseGenerator):
    """Generate a compact project card suitable for WordPress embedding."""

    def generate(self, profile: "ProjectProfile", output_path: Path) -> None:
        """Generate a single project card and write to file."""
        md = self.render_card(profile)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(md, encoding="utf-8")

    def generate_all(
        self, profiles: List["ProjectProfile"], output_dir: Path
    ) -> List[Path]:
        """Generate cards for all profiles. Returns list of written paths."""
        output_dir.mkdir(parents=True, exist_ok=True)
        paths = []
        for p in profiles:
            path = output_dir / f"{p.name}-card.md"
            self.generate(p, path)
            paths.append(path)
        return paths

    def render_card(self, p: "ProjectProfile") -> str:
        """Render a compact project card as markdown."""
        meta = p.metadata
        name = meta.name or p.name
        repo = meta.repository or f"{self.org_url}/{p.name}"
        lang = p.tech_stack.primary_language
        version = meta.version or "—"

        lines = [
            self._frontmatter(p),
            "",
            f"## [{name}]({repo})",
            "",
            self._badge_line(p),
            "",
            self._description(p),
            "",
            self._stats_table(p),
            "",
            self._features_line(p),
            "",
            self._deps_line(p),
            "",
            self._footer(),
        ]
        return "\n".join(lines)

    def _frontmatter(self, p: "ProjectProfile") -> str:
        return "\n".join([
            "---",
            f'title: "{p.metadata.name or p.name} — Project Card"',
            f'slug: "{p.name}-card"',
            f'date: "{self.generated_at}"',
            f'category: "{p.category}"',
            f'card_type: "project"',
            f'generated_by: "todocs"',
            "---",
        ])

    def _badge_line(self, p: "ProjectProfile") -> str:
        badges = []
        if p.metadata.version:
            badges.append(f"![v{p.metadata.version}](https://img.shields.io/badge/version-{p.metadata.version}-blue)")
        score_color = (
            "brightgreen" if p.maturity.score >= 70
            else "yellow" if p.maturity.score >= 40
            else "red"
        )
        badges.append(f"![{p.maturity.grade}](https://img.shields.io/badge/grade-{p.maturity.grade}-{score_color})")
        lang = p.tech_stack.primary_language
        if lang != "unknown":
            badges.append(f"![{lang}](https://img.shields.io/badge/lang-{lang}-informational)")
        return " ".join(badges)

    def _description(self, p: "ProjectProfile") -> str:
        desc = p.metadata.description or p.summary or "No description available."
        if len(desc) > 200:
            desc = desc[:197] + "..."
        return desc

    def _stats_table(self, p: "ProjectProfile") -> str:
        s = p.code_stats
        m = p.maturity
        return "\n".join([
            "| Metric | Value |",
            "|--------|------:|",
            f"| Source lines | {s.source_lines:,} |",
            f"| Source files | {s.source_files} |",
            f"| Test files | {s.test_files} |",
            f"| Maturity score | {m.score:.0f}/100 |",
            f"| Avg complexity | {s.avg_complexity:.1f} |",
        ])

    @staticmethod
    def _features_line(p: "ProjectProfile") -> str:
        icons = {
            "tests": ("✅", p.maturity.has_tests),
            "CI": ("✅", p.maturity.has_ci),
            "docs": ("✅", p.maturity.has_docs),
            "Docker": ("✅", p.maturity.has_docker),
            "changelog": ("✅", p.maturity.has_changelog),
        }
        parts = [f"{icon if present else '❌'} {label}" for label, (icon, present) in icons.items()]
        return "**Features:** " + " · ".join(parts)

    @staticmethod
    def _deps_line(p: "ProjectProfile") -> str:
        deps = p.dependencies[:6]
        if not deps:
            return "**Dependencies:** none"
        text = ", ".join(f"`{d}`" for d in deps)
        if len(p.dependencies) > 6:
            text += f" +{len(p.dependencies) - 6} more"
        return f"**Dependencies:** {text}"

    def _footer(self) -> str:
        return f"*Generated by [todocs](https://github.com/wronai/todocs) on {self.generated_at}.*"
